### ISSUE TITLE
which framework to use for model translation

### ISSUE THREAD

**Issue by camold** [tiangolo/pydantic-sqlalchemy#25]
Hi there,

thanks for all your efforts in getting this model translation to work! Really appreciated.
Upon a quick search (there really seems to be an entire zoo of possible orm's + pydantic + graphene models etc. etc.) I came upon this:
https://github.com/kolypto/py-sa2schema
From the descriptions and listed examples it seems they are trying to achieve the same thing.

Now the hard question: which one should I use?
Any opinions on pro- & cons?

Thanks,
Carsten

**Comment by DanLipsitt** [comment]
See also [tiangolo/sqlmodel](https://github.com/tiangolo/sqlmodel). Maybe @tiangolo can comment on whether he plans on SQLModel replacing pydantic-sqlalchemy.

**Comment by tiangolo** [comment]
Thank you all for the discussion! Yep, I built SQLModel as my best attempt at solving these problems. `pydantic-sqlalchemy` only partially solves some of the problems. But SQLModel is the best thing I could build for this. 🚀

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
