### ISSUE TITLE
What about pydantic_to_sqlalchemy?

### ISSUE THREAD

**Issue by mreiche** [tiangolo/pydantic-sqlalchemy#46]
Using `sqlalchemy_to_pydantic` helped me a lot, but now I need the other way around. Is it supposed to be part of this library?

Using `SQLModel` is no proper alternative to me, because it makes things harder, not easier right now.

**Comment by VSHUMILIN97** [comment]
It will certainly force you to use custom `FieldInfo`, since python int might be a: BigInt, Int, SmallInt. Same rules applies to str -> Text, String, UnicodeText, Unicode

And I do believe that it would be hard to get consistent dunder methods behaviour (eq, lt, gt and so on), because `pydantic.BaseModel` already provides this methods. Either it would be some serious context resolving feature (is it "pure python" or "ORM-python") or strange wrappings :)

**Comment by fkromer** [comment]
This discussion could be interesting for you: https://github.com/tiangolo/pydantic-sqlalchemy/issues/49#issuecomment-1312803122

**Comment by mreiche** [comment]
I've implemented a method on my own long ago and I want to share it here since this library seems to be orphaned.
```python
T = TypeVar('T')

def to_orm(
    source: BaseModel,
    target: T | Type[T],
    entity_callback: Callable[[T], None] = None
) -> Type[T]:

    if not isinstance(target, Base):
        target_class = target
        target = target_class()
    else:
        target_class = target.__class__

    if entity_callback:
        entity_callback(target)

    for var, value in vars(source).items():
        if not hasattr(target_class, var):
            continue

        if isinstance(value, BaseModel):
            sub_target = getattr(target, var)
            if sub_target:
                value = to_orm(value, sub_target)
            else:
                class_attrib = getattr(target_class, var)
                if isinstance(class_attrib.property, RelationshipProperty):
                    relationship: RelationshipProperty = class_attrib.property
                    value = to_orm(value, relationship.argument)

        setattr(target, var, value)

    return target
```

Can be used on instances:
```python
my_entity = to_orm(pydantic_model, MyEntity())
```
or classes
```python
my_entity = to_orm(pydantic_model, MyEntity)
```
Works well for me with `SQLAlchemy` 1 and 2, but could also work with other models, since it does only uses `setattr` on the instance.
