### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by bichanna** [tiangolo/pydantic-sqlalchemy#49]
Hi,
I like this package, and personally, I used it twice in my little projects.
There are some pull requests (including mine) that are not replied to. 
Is this project no longer maintained?
Thanks.

**Comment by fkromer** [comment]
tiangolo (the maintainer of this project) is the maintainer of FastAPI as well. In the FastAPI docs it's explained how most people use [pydantic schemas](https://fastapi.tiangolo.com/tutorial/sql-databases/#create-the-pydantic-models) in combination with [SQLAlchemy models](https://fastapi.tiangolo.com/tutorial/sql-databases/#create-the-database-models) to create [CRUD utils](https://fastapi.tiangolo.com/tutorial/sql-databases/#crud-utils) in FastAPI applications. However you can use the same methodology with any other backend framework making use of SQLAlchemy as well of course. I'd consider pydantic-sqlalchemy project deprecated.

**Comment by mreiche** [comment]
Too bad. SQLModel didn't work for me last time I used it.
